apiVersion: v1
kind: ServiceAccount
metadata:
  name: goserver-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: goserver-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: goserver-role-bind
subjects:
  - kind: ServiceAccount
    name: goserver-account
roleRef:
  kind: Role
  name: goserver-role
  apiGroup: rbac.authorization.k8s.io
