global:
route:
  receiver: Default
  group_by: ['alertname']
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 1m
  routes:
    - receiver: AlertaDatabase
      match:
        team: database
    - receiver: AlertaWeb
      match:
        team: web

receivers:
- name: Default
  telegram_config:
    - bot_token: 
      api_url:
      chat_id:
      parse_mode: ""
      message: "{{ range .Alerts }}{{ .Annotations.descricao }}\n{{ end }}"
- name: AlertaDatabase
  telegram_config:
    - bot_token: 
      api_url:
      chat_id:
      parse_mode: ""
      message: "{{ range .Alerts }}{{ .Annotations.descricao }}\n{{ end }}"
- name: AlertaWeb
  telegram_config:
    - bot_token: 
      api_url:
      chat_id:
      parse_mode: ""
      message: "{{ range .Alerts }}{{ .Annotations.descricao }}\n{{ end }}"