version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./alert-rules.yaml:/etc/prometheus/alert-rulers.rules
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  alertmanager:
    image: prom/alertmanager:v0.25.0
    ports:
      - 9093:9093
    volumes:
      - ./alert-manager.yaml:/prometheus/alertmanager.yml
    command: 
      - '--config.file=/prometheus/alertmanager.yml'
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: grafana
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    user: root
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    
  app:
    build: .
    container_name: app
    volumes:
      - .:/go/src
    ports:
      - 8181:8181
