{
 "title": "Goapp",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Online Users",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "goapp_online_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total de requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "goapp_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tempo de carregamento vs Acessos",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "goapp_http_request_duration_bucket{le=\"+Inf\"}",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}