# my global config
global:
  scrape_interval: 10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_timeout: 10s # 
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - alert-rulers.rules

# Alertmanager configuration
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
          - alertmanager:9093

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: goapp
    scrape_interval: 5s
    static_configs:
      - targets:
          - app:8181
