apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: deirofelippe/fullcycle-k8s:v2
          resources: {}
          volumeMounts:
            - mountPath: /home/devfc/app/.env
              name: env-file-volume
              readOnly: true
          envFrom:
            - configMapRef:
                name: "goserver-env"
      volumes:
        - name: env-file-volume
          configMap:
            name: goserver-env
            items:
              - key: NAME
                path: ".env"


