apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: deirofelippe/fullcycle-k8s:v1
          # securityContext:
          #   runAsUser: 0
          #   privileged: true
          # command:
          #   - sleep
          #   - infinity
