apiVersion: v1
kind: Service
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    app: "goserver"
  type: ClusterIP
  ports:
    - name: goserver-port
      port: 8000 # porta do servicej
      targetPort: 8000 # porta do container
      protocol: TCP
