name: ci-golang-workflow

env:
  WORKDIR: ./integracao-continua

on:
  pull_request:
    branches:
      - main

jobs:
  check-application:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [1.20.14, 1.23.3]

    steps:
      - uses: actions/checkout@v4

      - name: Use Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}

      - name: Go Init
        working-directory: ${{ env.WORKDIR }}
        run: |
          rm go.mod
          go mod init deirofelippe/math
          go mod tidy

      - name: Run Test
        working-directory: ${{ env.WORKDIR }}
        run: go test

      - name: Run Math
        working-directory: ${{ env.WORKDIR }}
        run: go run math.go

  build:
    needs: [check-application]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          context: ${{ env.WORKDIR }}
          file: ${{ env.WORKDIR }}/Dockerfile
          tags: deirofelippe/fullcycle-integracao-continua-ci:latest
