name: ci-golang-workflow

env:
  WORKDIR: ./integracao-continua

on: [push]

jobs:
  check-application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"

      - name: Run Test
        working-directory: ${{ env.WORKDIR }}
        run: go test

      - name: Run Math
        working-directory: ${{ env.WORKDIR }}
        run: go run math.go
