name: ci-golang-workflow

env:
  WORKDIR: ./integracao-continua

on:
  pull_request:
    branches:
      - main

jobs:
  check-application:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [1.20.14, 1.23.3]

    steps:
      - uses: actions/checkout@v4

      - name: Use Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}

      - name: Go Init
        working-directory: ${{ env.WORKDIR }}
        run: |
          rm go.mod
          go mod init deirofelippe/math
          go mod tidy

      - name: Run Test
        working-directory: ${{ env.WORKDIR }}
        run: go test

      - name: Run Math
        working-directory: ${{ env.WORKDIR }}
        run: go run math.go
